import type { Metadata } from 'next';
import {CalendarDays,ArrowUpRight,ArrowRight,Check,Clock3,Link2,ShieldCheck,Video,ChevronRight,Users,CalendarCheck} from 'lucide-react';
import {siteUrl} from '@/lib/site';
import s from './landing.module.css';
export const metadata:Metadata={
 title:'모아타임 · 일정 조율은 짧게, 좋은 만남은 길게',
 description:'Google 캘린더와 연결하는 일정 예약 서비스 모아타임. 예약 페이지를 만들고 링크를 공유해 커피챗, 상담, 미팅 시간을 간편하게 조율하세요.',
 alternates:{canonical:siteUrl},
 openGraph:{type:'website',locale:'ko_KR',url:siteUrl,siteName:'모아타임',title:'일정 조율은 짧게, 좋은 만남은 길게 · 모아타임',description:'가능한 시간을 모아, 예약 링크 하나로. 개인과 팀을 위한 Google 캘린더 기반 일정 예약.'},
 twitter:{card:'summary_large_image',title:'모아타임 · 좋은 만남을 위한 시간',description:'가능한 시간을 모아, 예약 링크 하나로.'},
 robots:{index:true,follow:true}
};
const faqs=[
 ['모아타임은 어떤 서비스인가요?','미팅 가능한 시간을 설정하고 예약 링크를 공유하는 일정 예약 서비스입니다. 커피챗, 프로젝트 상담, 서비스 데모 등 다양한 만남을 조율할 수 있습니다.'],
 ['로그인과 회원가입은 어떻게 하나요?','Google 계정으로만 시작할 수 있습니다. 처음 인증하면 회원가입이 진행되고, 기존 회원은 같은 계정으로 로그인합니다. 별도 비밀번호나 기업 SSO는 제공하지 않습니다.'],
 ['Google 캘린더의 기존 일정과 겹치지 않나요?','캘린더 연결 후 기존 일정이 있는 시간은 예약 후보에서 제외합니다. 예약을 확정하기 직전에도 일정을 다시 확인합니다. 캘린더 권한이 없거나 조회에 실패하면 예약을 진행하지 않습니다.'],
 ['예약 알림도 받을 수 있나요?','예약자와 주최자에게 보내는 이메일, 문자, 카카오 알림톡 연동을 준비하고 있습니다. 현재 공개 버전에서는 알림 발송이 꺼져 있으며, 연동이 완료된 채널부터 이용할 수 있습니다.']
];
export default function Landing(){return <div className={s.page}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'모아타임',url:siteUrl,inLanguage:'ko-KR',description:'Google 캘린더 기반 일정 예약 서비스'}).replace(/</g,'\\u003c')}}/>
<a className={s.skip} href="#main">본문으로 건너뛰기</a>
<header className={s.header}><a className={s.brand} href="/" aria-label="모아타임 홈"><span className={s.mark}><CalendarDays size={21}/></span>모아타임<span className={s.brandDot}>.</span></a><nav className={s.nav} aria-label="메인 메뉴"><a href="#features">서비스 소개</a><a href="#how">이용 방법</a><a href="#faq">자주 묻는 질문</a></nav><div className={s.navActions}><a href="/login">로그인</a><a className={s.smallCta} href="/login">회원가입 <ArrowUpRight size={15}/></a></div></header>
<main id="main" className={s.main}>
<section className={s.hero}><div className={s.heroCopy}><span className={s.badge}><span/> 더 좋은 만남을 위한 시간</span><h1>일정 조율은 짧게,<br/>좋은 만남은 <span>길게.</span></h1><p>“언제 시간 괜찮으세요?” 대신 링크 하나.<br/>서로의 가능한 시간을 모아,<br className={s.mobileBreak}/> 만남에 더 집중하세요.</p><div className={s.heroActions}><a className={s.cta} href="/login">Google로 시작하기 <ArrowRight size={18}/></a><a className={s.textLink} href="#how">어떻게 사용하나요? <ChevronRight size={16}/></a></div><div className={s.heroNote}><span className={s.googleLetter}>G</span>Google 계정으로 간편하게 · 개인도, 팀도</div></div>
<div className={s.heroVisual} aria-label="예약 페이지 예시"><div className={s.visualTop}><span><i/><i/><i/></span><small>moatime / your-next-meeting</small><ShieldCheck size={14}/></div><div className={s.preview}><div className={s.meeting}><div className={s.profileIcon}>M<span/></div><small>모아 스튜디오</small><h2>우리, 잠깐<br/>이야기 나눠요.</h2><p>새로운 아이디어가 시작되는<br/>가벼운 커피챗 ☕</p><span><Clock3 size={14}/>30분</span><span><Video size={14}/>온라인 미팅</span><div className={s.previewLabel}>예약 화면 예시</div></div><div className={s.calendar}><div className={s.calendarHeading}><b>편한 시간을 선택하세요</b><CalendarDays size={16}/></div><p>2026년 10월 <span>‹　›</span></p><div className={s.calendarGrid}>{['월','화','수','목','금','토','일'].map(d=><small key={d}>{d}</small>)}{Array.from({length:28},(_,i)=><span className={i===13?s.selectedDay:i>9&&i<19?s.availableDay:''} key={i}>{i+1}</span>)}</div><div className={s.times}><span>10:00</span><span className={s.selectedTime}>14:00 <Check size={12}/></span><span>16:30</span></div><small className={s.timezone}>Asia/Seoul · 한국 표준시</small></div></div><div className={s.floatingNote}><span><CalendarCheck size={20}/></span><div><b>딱 맞는 시간을 찾았어요!</b><small>10월 14일 · 오후 2:00</small></div><Check size={16}/></div><span className={s.orbitOne}/><span className={s.orbitTwo}/></div></section>
<div className={s.useCases}><p>시간을 맞춰야 하는 모든 순간에</p><div><span>☕ 커피챗</span><span>✦ 프로젝트 상담</span><span>◈ 서비스 데모</span><span>↗ 파트너 미팅</span></div></div>
<section id="features" className={s.features}><div className={s.sectionHeading}><span className={s.eyebrow}>LESS BACK AND FORTH</span><h2>주고받는 메시지는 줄이고,<br/>함께하는 시간은 늘리고.</h2><p>약속 하나를 잡기 위해 여러 번 확인하지 않아도 되도록.</p></div><div className={s.featureGrid}><article className={s.featureCard}><span className={s.featureIcon}><CalendarDays/></span><h3>내 캘린더에 맞춰,<br/>가능한 시간만.</h3><p>Google 캘린더의 바쁜 시간을 제외하고<br/>새로운 만남이 가능한 시간을 보여줍니다.</p><div className={s.busyDemo}><span>10:00 <i>기존 일정</i></span><span>11:00 <b>예약 가능 <Check size={13}/></b></span><span>14:00 <i>기존 일정</i></span></div></article><article className={s.featureCard}><span className={s.featureIcon}><Link2/></span><h3>설명은 간단하게,<br/>공유는 링크 하나로.</h3><p>미팅 목적과 시간을 정해 예약 페이지를 만들고,<br/>메신저나 이메일로 링크를 전달하세요.</p><div className={s.linkDemo}><span>moatime / coffee-chat</span><Link2 size={17}/></div><div className={s.tagRow}><span>커피챗</span><span>30분</span><span>온라인</span></div></article><article className={s.featureCard}><span className={s.featureIcon}><Users/></span><h3>혼자 하는 일부터,<br/>함께하는 미팅까지.</h3><p>상담, 커피챗, 서비스 소개까지.<br/>만남의 목적에 맞는 예약 페이지를 관리하세요.</p><div className={s.stackDemo}><span><i>☕</i>가볍게 나누는 커피챗<small>30분</small></span><span><i>✦</i>프로젝트 상담<small>60분</small></span></div></article></div></section>
<section id="how" className={s.how}><div className={s.howIntro}><span className={s.eyebrow}>SIMPLE AS ONE, TWO, THREE</span><h2>다음 만남까지,<br/>세 단계면 충분해요.</h2><p>복잡한 설정 대신<br/>나에게 맞는 예약 흐름을 만들어보세요.</p><a className={s.textLink} href="/login">내 예약 페이지 만들기 <ArrowRight size={17}/></a></div><ol className={s.steps}>{[['01','나의 가능한 시간을 정해요','Google 계정을 연결하고, 미팅을 받을 요일과 시간을 설정하세요.'],['02','예약 링크를 공유해요','커피챗, 상담 등 목적에 맞는 예약 페이지를 만들어 전달하세요.'],['03','선택한 시간에 만나요','상대방이 Google로 로그인해 시간을 선택하면, 예약된 일정을 한곳에서 확인하세요.']].map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>
<section id="faq" className={s.faq}><div className={s.sectionHeading}><span className={s.eyebrow}>GOOD TO KNOW</span><h2>궁금한 점이 있으신가요?</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className={s.finalCta}><span className={s.eyebrow}>MAKE TIME FOR WHAT MATTERS</span><h2>시간을 맞추는 일보다,<br/>함께할 이야기에 집중하세요.</h2><a className={s.cta} href="/login">나의 첫 예약 페이지 만들기 <ArrowRight size={18}/></a><p>Google 계정으로 시작하는 더 간편한 일정 조율</p></section>
</main><footer className={s.footer}><div><a className={s.brand} href="/"><span className={s.mark}><CalendarDays size={19}/></span>모아타임<span className={s.brandDot}>.</span></a><p>시간을 모아, 더 좋은 만남으로.</p></div><div><a href="#features">서비스 소개</a><a href="#faq">자주 묻는 질문</a><a href="/login">로그인 / 회원가입</a></div><small>© {new Date().getFullYear()} 모아타임</small></footer></div>}
