"use client";
import {meetingFields,type MeetingSettings} from '@/lib/bookings/meeting';
import {useEffect,useState} from 'react';
import AvailabilityCalendar from './availability-calendar';
import {addDays,kstDay,permitsTime,type Availability} from '@/lib/availability';
import {availableSlots,type Busy} from '@/lib/calendar/google';
type Event=MeetingSettings & {id:string;title:string;desc:string;duration:number;color:string;team:boolean;active:boolean;availability?:Availability};
export default function EventEditor({initial,team,hours,range,onSave,busy}:{initial?:Event;team:boolean;hours:boolean[];range:string[];onSave:(e:Event)=>Promise<boolean>;busy:boolean}){
  const [companyMode,CM]=useState<NonNullable<MeetingSettings['companyMode']>>(initial?.companyMode||'hidden'),[meetingTitleTemplate,MT]=useState(initial?.meetingTitleTemplate||'{회사명} × 셀리즈 미팅');
  const today=kstDay(),[title,T]=useState(initial?.title||''),[desc,D]=useState(initial?.desc||''),[duration,DU]=useState(initial?.duration||30);
  const [availability,A]=useState<Availability>(initial?.availability||{days:{},includeWeekends:false,includeLunch:false,source:'manual',updatedAt:new Date().toISOString()}),[start,ST]=useState(today),[end,EN]=useState(addDays(today,29)),[day,DAY]=useState(today),[month,MO]=useState(today.slice(0,7)),[loading,L]=useState(false),[error,E]=useState('');
  const [constraints,C]=useState<{busy:Busy[];holidays:Record<string,string>;start:string;end:string;checkedAt:string}|null>(null),[checking,CK]=useState(true);
  const includeWeekends=availability.includeWeekends!==false,includeLunch=availability.includeLunch!==false;
  const excludeHolidays=availability.excludeHolidays!==false;
  async function refreshConstraints(){CK(true);E('');try{const r=await fetch('/api/availability/constraints',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);C(d)}catch(e){C(null);E(e instanceof Error?e.message:'일정을 확인하지 못했습니다.')}finally{CK(false)}}
  useEffect(()=>{void refreshConstraints()},[]);
  function free(d:string,week:boolean[],span:string[]){return !constraints||(excludeHolidays&&constraints.holidays[d])?[]:availableSlots(d,duration,week,span,constraints.busy).filter(t=>permitsTime(availability,d,t,duration))}
  const allWeek=[true,true,true,true,true,true,true];
  const displayDays=Object.fromEntries(Object.entries(availability.days).map(([d,slots])=>{const allowed=free(d,allWeek,['00:00','23:59']);return [d,slots.filter(t=>allowed.includes(t))]}));
  const allowed=free(day,allWeek,['00:00','23:59']);
  const times=availableSlots(day,duration,[true,true,true,true,true,true,true],['00:00','23:59'],[]);
  const selected=displayDays[day]||[],count=Object.values(displayDays).reduce((n,s)=>n+s.length,0);
  function update(days:Record<string,string[]>){A({...availability,days,updatedAt:new Date().toISOString()})}
  function valid(){if(start<today||end<start||end>addDays(today,90)){E('오늘부터 90일 이내의 기간을 선택해 주세요.');return false}return true}
  function applyWeekly(){if(!valid())return;const days={...availability.days};for(let d=start;d<=end;d=addDays(d,1))days[d]=free(d,hours.map((v,i)=>i===0||i===6?includeWeekends:v),range);A({days,includeWeekends,includeLunch,excludeHolidays,source:'manual',updatedAt:new Date().toISOString()});E('');MO(start.slice(0,7));DAY(start)}
  async function importCalendar(){if(!valid())return;L(true);E('');try{const r=await fetch('/api/availability/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start,end,duration,hours,range,excludeHolidays,includeWeekends,includeLunch})});const data=await r.json();if(!r.ok)throw Error(data.error);A({...data.availability,days:{...availability.days,...data.availability.days}});MO(start.slice(0,7));DAY(start)}catch(e){E(e instanceof Error?e.message:'가져오기 실패')}finally{L(false)}}
  return <form className="event-editor" onSubmit={async e=>{e.preventDefault();if(!constraints||checking)return;await onSave({id:initial?.id||crypto.randomUUID(),title,desc,duration,companyMode,meetingTitleTemplate,color:initial?.color||'blue',team:initial?.team??team,active:initial?.active??true,availability:{...availability,days:Object.fromEntries(Object.entries(availability.days).filter(([d])=>d>=today&&d<=addDays(today,90)))}})}}><span className="tag">{initial?'EDIT AVAILABILITY':'NEW EVENT'}</span><h2>{initial?'만남과 가능 시간 수정':'어떤 만남을 만들까요?'}</h2><p>가능한 날짜와 시작 시간을 선택해 저장하세요.</p>
  <div className="notice" role="status">{checking?'Google 일정과 대한민국 공휴일 확인 중…':constraints?<>일정 확인 범위: {constraints.start} ~ {constraints.end}<br/>Google 일정과 겹치는 시간은 선택할 수 없습니다.</>:'일정을 확인해야 가능 시간을 설정할 수 있습니다.'}<button type="button" disabled={checking||busy||loading} onClick={refreshConstraints}>일정 다시 불러오기</button></div><fieldset disabled={busy||loading||checking||!constraints}><label>페이지 이름<input required maxLength={60} value={title} onChange={e=>T(e.target.value)} placeholder="예: 30분 커피챗" autoFocus/></label><label>회사명 입력<select value={companyMode} onChange={e=>CM(e.target.value as NonNullable<MeetingSettings['companyMode']>)}><option value="hidden">사용 안 함</option><option value="optional">선택 입력</option><option value="required">필수 입력</option></select></label>{companyMode!=='hidden'&&<><label>미팅 제목 규칙<input value={meetingTitleTemplate} maxLength={100} onChange={e=>MT(e.target.value)} placeholder="{회사명} × 셀리즈 미팅"/></label><small>{'{회사명}, {페이지명}을 사용할 수 있습니다. 회사명이 없으면 페이지 이름을 사용합니다.'}</small><p>예시: {meetingFields({title:title||'파트너 미팅',companyMode,meetingTitleTemplate},'ABC파트너스').meetingTitle}</p></>}<label>소개<textarea maxLength={150} value={desc} onChange={e=>D(e.target.value)}/></label><label>소요 시간<select value={duration} onChange={e=>{DU(Number(e.target.value));A({days:{},includeWeekends,includeLunch,excludeHolidays,source:'manual',updatedAt:new Date().toISOString()});E('소요 시간이 바뀌었습니다. 가능한 시간을 다시 선택해 주세요.')}}><option value={15}>15분</option><option value={30}>30분</option><option value={60}>60분</option></select></label>
  <div className="availability-tools"><h3>가능 시간 설정</h3><p>달력에서 날짜를 눌러 직접 선택하거나, 지정한 기간을 한 번에 채우세요.</p><label><input type="checkbox" checked={includeWeekends} onChange={e=>A({...availability,includeWeekends:e.target.checked,updatedAt:new Date().toISOString()})}/>주말 포함 (토·일)</label><label><input type="checkbox" checked={includeLunch} onChange={e=>A({...availability,includeLunch:e.target.checked,updatedAt:new Date().toISOString()})}/>점심시간 포함 (12:00–13:00 · 한국시간)</label><label><input type="checkbox" checked={excludeHolidays} onChange={e=>A({...availability,excludeHolidays:e.target.checked,updatedAt:new Date().toISOString()})}/>대한민국 공휴일 자동 제외 (대체공휴일 포함)</label><div className="date-range"><label>시작일<input type="date" min={today} max={addDays(today,90)} value={start} onChange={e=>ST(e.target.value)}/></label><label>종료일<input type="date" min={start} max={addDays(today,90)} value={end} onChange={e=>EN(e.target.value)}/></label></div><div className="availability-actions"><button type="button" onClick={applyWeekly}>주간 가능 시간으로 채우기</button><button type="button" onClick={importCalendar}>{loading?'Google 일정 가져오는 중…':'Google 빈 시간 자동 선택'}</button></div><small>주말·점심·공휴일 옵션 적용 · 주간 설정 {range[0]}–{range[1]} 적용 · 해당 기간의 선택을 교체합니다.</small></div>
  <div className="availability-editor-grid"><AvailabilityCalendar month={month} onMonth={v=>{MO(v);DAY(v===today.slice(0,7)?today:v+'-01')}} day={day} onDay={DAY} days={displayDays} editing/><div><h3>{day} · 시작 시간 ({duration}분 간격)</h3>{excludeHolidays&&constraints?.holidays[day]&&<p role="status">대한민국 공휴일 · 예약에서 제외됩니다.</p>}<div className="availability-actions"><button type="button" onClick={()=>update({...availability.days,[day]:free(day,allWeek,range)})}>기본 시간 선택</button><button type="button" onClick={()=>update({...availability.days,[day]:[]})}>이 날짜 비우기</button></div><div className="slots editable-slots">{times.map(time=><button type="button" key={time} disabled={!allowed.includes(time)} title={!allowed.includes(time)?'Google 일정 또는 주말·점심·공휴일 설정으로 예약 불가':undefined} aria-pressed={selected.includes(time)} className={selected.includes(time)?'picked':''} onClick={()=>update({...availability.days,[day]:selected.includes(time)?selected.filter(t=>t!==time):[...selected,time].sort()})}>{time}</button>)}</div></div></div>
  <div className="notice">{Object.values(displayDays).filter(s=>s.length).length}일 · {count}개 시작 시간 선택됨{availability.source==='google'&&<><br/>Google 가져오기 기준: {new Date(availability.importedAt||availability.updatedAt).toLocaleString('ko-KR')}<br/>로그인·서비스 접속 시 Google 일정을 다시 확인해 겹치는 시간을 자동 제외합니다.</>}<br/>이미 예약된 시간은 모든 예약 페이지에서 자동으로 제외됩니다.</div></fieldset>
  {error&&<p role="alert" className="notice">{error}</p>}<button className="primary full" disabled={busy||loading||checking||!constraints}>{busy?'저장 중…':initial?'변경사항 저장':'예약 페이지 만들기'}</button><p className="muted">시간을 선택하지 않고 저장하면 예약을 받을 수 없습니다.</p></form>;
}
