"use client";
import {useState} from 'react';
import AvailabilityCalendar from './availability-calendar';
import {addDays,kstDay,type Availability} from '@/lib/availability';
import {availableSlots} from '@/lib/calendar/google';
type Event={id:string;title:string;desc:string;duration:number;color:string;team:boolean;active:boolean;availability?:Availability};
export default function EventEditor({initial,team,hours,range,onSave,busy}:{initial?:Event;team:boolean;hours:boolean[];range:string[];onSave:(e:Event)=>Promise<boolean>;busy:boolean}){
  const today=kstDay(),[title,T]=useState(initial?.title||''),[desc,D]=useState(initial?.desc||''),[duration,DU]=useState(initial?.duration||30);
  const [availability,A]=useState<Availability>(initial?.availability||{days:{},source:'manual',updatedAt:new Date().toISOString()}),[start,ST]=useState(today),[end,EN]=useState(addDays(today,29)),[day,DAY]=useState(today),[month,MO]=useState(today.slice(0,7)),[loading,L]=useState(false),[error,E]=useState('');
  const times=availableSlots(day,duration,[true,true,true,true,true,true,true],['00:00','23:59'],[]);
  const selected=availability.days[day]||[],count=Object.values(availability.days).reduce((n,s)=>n+s.length,0);
  function update(days:Record<string,string[]>){A({...availability,days,updatedAt:new Date().toISOString()})}
  function valid(){if(start<today||end<start||end>addDays(today,90)){E('오늘부터 90일 이내의 기간을 선택해 주세요.');return false}return true}
  function applyWeekly(){if(!valid())return;const days={...availability.days};for(let d=start;d<=end;d=addDays(d,1))days[d]=availableSlots(d,duration,hours,range,[]);A({days,source:'manual',updatedAt:new Date().toISOString()});E('');MO(start.slice(0,7));DAY(start)}
  async function importCalendar(){if(!valid())return;L(true);E('');try{const r=await fetch('/api/availability/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start,end,duration,hours,range})});const data=await r.json();if(!r.ok)throw Error(data.error);A({...data.availability,days:{...availability.days,...data.availability.days}});MO(start.slice(0,7));DAY(start)}catch(e){E(e instanceof Error?e.message:'가져오기 실패')}finally{L(false)}}
  return <form className="event-editor" onSubmit={async e=>{e.preventDefault();await onSave({id:initial?.id||crypto.randomUUID(),title,desc,duration,color:initial?.color||'blue',team:initial?.team??team,active:initial?.active??true,availability:{...availability,days:Object.fromEntries(Object.entries(availability.days).filter(([d])=>d>=today&&d<=addDays(today,90)))}})}}><span className="tag">{initial?'EDIT AVAILABILITY':'NEW EVENT'}</span><h2>{initial?'만남과 가능 시간 수정':'어떤 만남을 만들까요?'}</h2><p>가능한 날짜와 시작 시간을 선택해 저장하세요.</p>
  <fieldset disabled={busy||loading}><label>페이지 이름<input required maxLength={60} value={title} onChange={e=>T(e.target.value)} placeholder="예: 30분 커피챗" autoFocus/></label><label>소개<textarea maxLength={150} value={desc} onChange={e=>D(e.target.value)}/></label><label>소요 시간<select value={duration} onChange={e=>{DU(Number(e.target.value));A({days:{},source:'manual',updatedAt:new Date().toISOString()});E('소요 시간이 바뀌었습니다. 가능한 시간을 다시 선택해 주세요.')}}><option value={15}>15분</option><option value={30}>30분</option><option value={60}>60분</option></select></label>
  <div className="availability-tools"><h3>가능 시간 설정</h3><p>달력에서 날짜를 눌러 직접 선택하거나, 지정한 기간을 한 번에 채우세요.</p><div className="date-range"><label>시작일<input type="date" min={today} max={addDays(today,90)} value={start} onChange={e=>ST(e.target.value)}/></label><label>종료일<input type="date" min={start} max={addDays(today,90)} value={end} onChange={e=>EN(e.target.value)}/></label></div><div className="availability-actions"><button type="button" onClick={applyWeekly}>주간 가능 시간으로 채우기</button><button type="button" onClick={importCalendar}>{loading?'Google 일정 가져오는 중…':'Google 빈 시간 자동 선택'}</button></div><small>공휴일 구독 캘린더 제외 · 주간 설정 {range[0]}–{range[1]} 적용 · 해당 기간의 선택을 교체합니다.</small></div>
  <div className="availability-editor-grid"><AvailabilityCalendar month={month} onMonth={v=>{MO(v);DAY(v===today.slice(0,7)?today:v+'-01')}} day={day} onDay={DAY} days={availability.days} editing/><div><h3>{day} · 시작 시간</h3><div className="availability-actions"><button type="button" onClick={()=>update({...availability.days,[day]:availableSlots(day,duration,[true,true,true,true,true,true,true],range,[])})}>기본 시간 선택</button><button type="button" onClick={()=>update({...availability.days,[day]:[]})}>이 날짜 비우기</button></div><div className="slots editable-slots">{times.map(time=><button type="button" key={time} aria-pressed={selected.includes(time)} className={selected.includes(time)?'picked':''} onClick={()=>update({...availability.days,[day]:selected.includes(time)?selected.filter(t=>t!==time):[...selected,time].sort()})}>{time}</button>)}</div></div></div>
  <div className="notice">{Object.values(availability.days).filter(s=>s.length).length}일 · {count}개 시작 시간 선택됨{availability.source==='google'&&<><br/>Google 가져오기 기준: {new Date(availability.importedAt||availability.updatedAt).toLocaleString('ko-KR')}<br/>이후 Google 일정 변경은 다시 가져온 뒤 저장해 주세요.</>}<br/>이미 예약된 시간은 모든 예약 페이지에서 자동으로 제외됩니다.</div></fieldset>
  {error&&<p role="alert" className="notice">{error}</p>}<button className="primary full" disabled={busy||loading}>{busy?'저장 중…':initial?'변경사항 저장':'예약 페이지 만들기'}</button><p className="muted">시간을 선택하지 않고 저장하면 예약을 받을 수 없습니다.</p></form>;
}
