"use client";
import {useEffect,useState,useRef} from 'react';
import {CalendarDays,Clock3,ShieldCheck} from 'lucide-react';
import AvailabilityCalendar from './availability-calendar';
import {guestContactSchema} from '@/lib/bookings/guest';
import {submitGuestBooking} from '@/lib/bookings/submit-guest';
import {meetingFields,type MeetingSettings} from '@/lib/bookings/meeting';
import {kstDay} from '@/lib/availability';
type Data={event:MeetingSettings & {desc:string;duration:number};days:Record<string,string[]>;availabilityReady:boolean;mode:string;user:{name:string;email:string}|null};
export default function BookingPage({id}:{id:string}){
  const [company,CO]=useState(''),[confirmedTitle,CT]=useState('');
  useEffect(()=>{CO((new URLSearchParams(location.hash.slice(1)).get('company')||sessionStorage.getItem('moa-company-'+id)||'').replace(/[\r\n\u0000-\u001f]/g,'').slice(0,80))},[]);
  const [data,D]=useState<Data|null>(null),[month,MO]=useState(kstDay().slice(0,7)),[day,DAY]=useState(''),[time,T]=useState(''),[error,E]=useState(''),[loading,L]=useState(true),[saving,S]=useState(false),[done,DONE]=useState(false),[bookingId,ID]=useState(''),[refresh,R]=useState(0),[receiptEmail,RE]=useState(''),[manageUrl,MU]=useState('');
  const [submitError,SE]=useState(''),[uncertain,U]=useState(false);const pendingRequest=useRef<Record<string,unknown>|null>(null);const submitting=useRef(false),errorBox=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(submitError)errorBox.current?.focus()},[submitError]);
  useEffect(()=>{ID(crypto.randomUUID())},[]);
  useEffect(()=>{if(done||saving||uncertain)return;const c=new AbortController();L(true);fetch(`/api/public/${id}?month=${month}`,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok){D(null);DAY('');T('');throw Error(d.error)}E('');return d as Data}).then(d=>{D(d);DAY(previous=>previous.startsWith(month)&&d.days[previous]?.length?previous:Object.keys(d.days).find(day=>d.days[day].length)||'')}).catch(e=>{if(e.name!=='AbortError')E(e.message)}).finally(()=>{if(!c.signal.aborted)L(false)});return ()=>c.abort()},[id,month,refresh,done,saving,uncertain]);
  useEffect(()=>{if(done||saving||uncertain)return;const update=()=>{if(document.visibilityState==='visible')R(n=>n+1)};const interval=setInterval(update,20000);window.addEventListener('focus',update);return ()=>{clearInterval(interval);window.removeEventListener('focus',update)}},[done,saving,uncertain]);
  useEffect(()=>{if(!done&&!saving&&!uncertain&&time&&!data?.days[day]?.includes(time))T('')},[data,day,time,done,saving,uncertain]);
  async function reserve(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();if(submitting.current)return;const form=e.currentTarget,f=new FormData(form);SE('');
    const contact=guestContactSchema.safeParse(pendingRequest.current||{name:f.get('name'),email:f.get('email'),phone:f.get('phone')||''});
    if(!contact.success){SE(contact.error.issues[0].message);return}
    if(!time||!day){SE('예약할 날짜와 시간을 선택해 주세요.');return}
    submitting.current=true;S(true);
    try{
      const requestId=bookingId||crypto.randomUUID();if(!bookingId)ID(requestId);
      const requestBody=pendingRequest.current||{id:requestId,day,time,company,...contact.data,channels:f.getAll('channels'),notificationConsent:f.get('consent')==='on'};
      pendingRequest.current=requestBody;
      const result=await submitGuestBooking(id,requestBody);
      if(!result.ok){const ambiguous=result.status===0||result.status>=500||result.status===200;U(ambiguous);if(!ambiguous)pendingRequest.current=null;if(result.status===409){T('');R(n=>n+1)}SE(result.error);return}
      CT(result.meetingTitle||'');RE(contact.data.email);MU(result.manageUrl||'');DONE(true);
    }finally{submitting.current=false;S(false)}
  }
  return <div className="public-booking"><a href="/" className="brand"><span className="logo"><CalendarDays/></span>모아타임.</a><section className="panel public-panel public-calendar-panel"><span className="tag">BOOK A TIME</span><h1>{done?'예약이 확정되었습니다':data?(company.trim()?meetingFields({...data.event,companyMode:data.event.companyMode==='hidden'?'hidden':'optional'},company).meetingTitle:data.event.title):'일정 예약'}</h1><p>{data?.event.desc}</p>{data&&<p><Clock3 size={15} style={{display:'inline',verticalAlign:'middle'}}/> {data.event.duration}분 · 한국시간 (Asia/Seoul)</p>}{submitError&&!time&&<div ref={errorBox} tabIndex={-1} className="notice" role="alert">{submitError}</div>}{error&&<div className="notice" role="alert">{error}<button type="button" onClick={()=>{E('');R(n=>n+1)}}>다시 확인</button></div>}
  {done?<><h2>{confirmedTitle}</h2><h2>{day} · {time}</h2><p>{receiptEmail}</p><div className="notice">이 시간은 다른 사람이 예약할 수 없도록 처리했습니다. 주최자의 Google 캘린더 등록도 자동으로 진행합니다.</div><p>{data?.mode==='live'?'예약자와 주최자 이메일로 알림 발송을 요청했습니다.':'현재 알림 발송은 꺼져 있거나 모의 발송 상태입니다.'}</p><p>예약 시작 전까지 확인 이메일의 전용 링크에서 변경·취소할 수 있습니다.</p>{manageUrl&&<a className="primary" href={manageUrl}>예약 변경·취소</a>}</>:error&&!data?<p>예약 페이지를 사용할 수 없습니다. 주최자에게 새 예약 링크를 요청해 주세요.</p>:<><h2 className="booking-step-title">편한 날짜와 시간을 선택하세요</h2><p>주최자가 열어 둔 시간만 표시됩니다. 본인 일정과 비교해 선택해 주세요.</p><div className="guest-calendar-grid"><AvailabilityCalendar month={month} onMonth={v=>{MO(v);DAY('');T('');E('')}} day={day} onDay={v=>{DAY(v);T('');E('')}} days={data?.days||{}} loading={loading||saving||uncertain}/><div className="guest-times"><h3>{day||'가능한 날짜를 선택하세요'}</h3>{loading&&<p role="status">가능 시간을 불러오는 중…</p>}{!loading&&data&&!data.availabilityReady&&<p>주최자가 가능한 날짜를 준비하고 있습니다.</p>}{!loading&&data&&!Object.values(data.days).some(s=>s.length)&&<p>이 달에는 예약 가능한 시간이 없습니다. 다른 달을 확인해 주세요.</p>}<div className="slots">{(data?.days[day]||[]).map(s=><button type="button" key={s} disabled={loading||saving||uncertain} aria-pressed={time===s} className={s===time?'picked':''} onClick={()=>{T(s);E('')}}>{s}</button>)}</div></div></div>
  {data&&!data.user&&<div className="notice"><p>로그인 없이 예약할 수 있습니다. Google로 로그인하면 이름과 이메일을 자동으로 채워드립니다.</p><a className="authbutton" onClick={()=>sessionStorage.setItem('moa-company-'+id,company)} href={'/auth/google?next='+encodeURIComponent('/book/'+id)}>Google로 계속하기 (선택)</a></div>}{time&&data&&<form className="public-form" onSubmit={reserve} onChange={()=>SE('')} aria-busy={saving}><h3>{day} · {time} 예약</h3>{data.event.companyMode&&data.event.companyMode!=='hidden'&&<><label>회사명{data.event.companyMode==='optional'?' (선택)':''}<input name="company" value={company} onChange={e=>CO(e.target.value.replace(/[\u0000-\u001f]/g,''))} maxLength={80} required={data.event.companyMode==='required'} disabled={saving||uncertain} autoComplete="organization" placeholder="예: ABC파트너스"/></label><p>미팅 제목: {company.trim()?meetingFields({...data.event,companyMode:'optional'},company).meetingTitle:data.event.title}</p></>}<label>이름<input disabled={saving||uncertain} name="name" required maxLength={80} autoComplete="name" defaultValue={data.user?.name||''}/></label><label>알림받을 이메일<input disabled={saving||uncertain} name="email" type="email" required maxLength={200} autoComplete="email" defaultValue={data.user?.email||''} placeholder="you@example.com"/></label><label>연락처<input disabled={saving||uncertain} name="phone" type="tel" required maxLength={20} autoComplete="tel" placeholder="01012345678" aria-describedby="phone-help"/></label><small id="phone-help">휴대전화 번호를 입력해 주세요. 예: 010-1234-5678</small><fieldset className="channel-options"><legend>예약 확정·취소 알림</legend><p>예약자와 주최자에게 이메일을 보냅니다.</p><label><input disabled={saving||uncertain} type="checkbox" name="channels" value="sms"/>문자도 받기</label><label><input disabled={saving||uncertain} type="checkbox" name="channels" value="kakao"/>카카오 알림톡도 받기</label><label><input disabled={saving||uncertain} type="checkbox" name="consent" required/>예약 처리와 선택한 채널의 예약 알림을 위해 입력한 연락처를 사용하는 것에 동의합니다.</label></fieldset>{submitError&&<div ref={errorBox} tabIndex={-1} role="alert" className="notice">{submitError}</div>}<button className="primary full" disabled={saving||loading}>{saving?'예약 확인 중…':uncertain?'예약 완료 여부 다시 확인':'예약 확정'}</button></form>}</>}
  <div className="footnote"><ShieldCheck size={15}/>예약된 시간은 자동으로 제외됩니다. 주최자의 비공개 일정 제목·내용은 표시하지 않습니다.</div></section></div>;
}
