"use client";
import {useEffect,useState} from 'react';
import {CalendarDays,Clock3,ShieldCheck} from 'lucide-react';
import AvailabilityCalendar from './availability-calendar';
import {kstDay} from '@/lib/availability';
type Data={event:{title:string;desc:string;duration:number};days:Record<string,string[]>;availabilityReady:boolean;mode:string;user:{name:string;email:string}|null};
export default function BookingPage({id}:{id:string}){
  const [data,D]=useState<Data|null>(null),[month,MO]=useState(kstDay().slice(0,7)),[day,DAY]=useState(''),[time,T]=useState(''),[error,E]=useState(''),[loading,L]=useState(true),[saving,S]=useState(false),[done,DONE]=useState(false),[bookingId,ID]=useState(''),[refresh,R]=useState(0);
  useEffect(()=>{ID(crypto.randomUUID())},[]);
  useEffect(()=>{if(done)return;const c=new AbortController();L(true);fetch(`/api/public/${id}?month=${month}`,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d as Data}).then(d=>{D(d);DAY(previous=>previous.startsWith(month)&&d.days[previous]?.length?previous:Object.keys(d.days).find(day=>d.days[day].length)||'')}).catch(e=>{if(e.name!=='AbortError')E(e.message)}).finally(()=>{if(!c.signal.aborted)L(false)});return ()=>c.abort()},[id,month,refresh,done]);
  useEffect(()=>{if(done)return;const update=()=>{if(document.visibilityState==='visible')R(n=>n+1)};const interval=setInterval(update,20000);window.addEventListener('focus',update);return ()=>{clearInterval(interval);window.removeEventListener('focus',update)}},[done]);
  useEffect(()=>{if(!done&&time&&!data?.days[day]?.includes(time))T('')},[data,day,time,done]);
  async function reserve(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);S(true);E('');try{const r=await fetch('/api/public/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:bookingId,day,time,name:f.get('name'),phone:f.get('phone')||'',channels:f.getAll('channels'),notificationConsent:f.get('consent')==='on'})});const d=await r.json();if(!r.ok){if(r.status===409){T('');R(n=>n+1)}throw Error(d.error)}DONE(true)}catch(e){E(e instanceof Error?e.message:'예약에 실패했습니다.')}finally{S(false)}}
  return <div className="public-booking"><a href="/" className="brand"><span className="logo"><CalendarDays/></span>모아타임.</a><section className="panel public-panel public-calendar-panel"><span className="tag">BOOK A TIME</span><h1>{done?'예약이 확정되었습니다':data?.event.title||'일정 예약'}</h1><p>{data?.event.desc}</p>{data&&<p><Clock3 size={15} style={{display:'inline',verticalAlign:'middle'}}/> {data.event.duration}분 · 한국시간 (Asia/Seoul)</p>}{error&&<div className="notice" role="alert">{error}<button type="button" onClick={()=>{E('');R(n=>n+1)}}>다시 확인</button></div>}
  {done?<><h2>{day} · {time}</h2><p>{data?.user?.email}</p><div className="notice">이 시간은 다른 사람이 예약할 수 없도록 처리했습니다. 주최자의 Google 캘린더 등록도 자동으로 진행합니다.</div><p>{data?.mode==='live'?'예약자와 주최자 이메일로 알림 발송을 요청했습니다.':'현재 알림 발송은 꺼져 있거나 모의 발송 상태입니다.'}</p><p>변경·취소가 필요한 경우 주최자에게 요청해 주세요.</p></>:<><h2 className="booking-step-title">편한 날짜와 시간을 선택하세요</h2><p>주최자가 열어 둔 시간만 표시됩니다. 본인 일정과 비교해 선택해 주세요.</p><div className="guest-calendar-grid"><AvailabilityCalendar month={month} onMonth={v=>{MO(v);DAY('');T('');E('')}} day={day} onDay={v=>{DAY(v);T('');E('')}} days={data?.days||{}} loading={loading}/><div className="guest-times"><h3>{day||'가능한 날짜를 선택하세요'}</h3>{loading&&<p role="status">가능 시간을 불러오는 중…</p>}{!loading&&data&&!data.availabilityReady&&<p>주최자가 가능한 날짜를 준비하고 있습니다.</p>}{!loading&&data&&!Object.values(data.days).some(s=>s.length)&&<p>이 달에는 예약 가능한 시간이 없습니다. 다른 달을 확인해 주세요.</p>}<div className="slots">{(data?.days[day]||[]).map(s=><button type="button" key={s} disabled={loading||saving} aria-pressed={time===s} className={s===time?'picked':''} onClick={()=>{T(s);E('')}}>{s}</button>)}</div></div></div>
  {data&&!data.user?<div className="notice"><p>예약자 확인과 알림 수신을 위해 Google 로그인이 필요합니다. 예약자의 캘린더 권한은 요청하지 않습니다.</p><a className="authbutton" href={'/auth/google?next='+encodeURIComponent('/book/'+id)}>Google로 계속하기</a></div>:time&&data?.user&&<form className="public-form" onSubmit={reserve}><h3>{day} · {time} 예약</h3><label>이름<input name="name" required maxLength={80} defaultValue={data.user.name}/></label><label>이메일<input readOnly value={data.user.email}/></label><label>휴대전화 (문자·알림톡 선택 시)<input name="phone" type="tel" placeholder="01012345678"/></label><fieldset className="channel-options"><legend>예약 확정·취소 알림</legend><p>예약자와 주최자에게 이메일을 보냅니다.</p><label><input type="checkbox" name="channels" value="sms"/>문자도 받기</label><label><input type="checkbox" name="channels" value="kakao"/>카카오 알림톡도 받기</label><label><input type="checkbox" name="consent" required/>예약 처리와 선택한 채널의 예약 알림을 위해 입력한 연락처를 사용하는 것에 동의합니다.</label></fieldset><button className="primary full" disabled={saving||loading||!!error}>{saving?'예약 확인 중…':'예약 확정'}</button></form>}</>}
  <div className="footnote"><ShieldCheck size={15}/>예약된 시간은 자동으로 제외됩니다. 주최자의 비공개 일정 제목·내용은 표시하지 않습니다.</div></section></div>;
}
