'use client';
import {useEffect,useState} from 'react';
import EventEditor from './event-editor';
import {rankSlots,type Poll} from '@/lib/polls/model';
export default function Polls({hours,range}:{hours:boolean[];range:string[]}){
 const [polls,P]=useState<Poll[]>([]),[selected,S]=useState<Poll|null>(null),[editing,E]=useState<'create'|'add'|null>(null),[expected,EX]=useState(2),[busy,B]=useState(false),[message,M]=useState('');
 async function request(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const d=await r.json();if(!r.ok)throw Error(d.error||'처리 실패');return d}
 async function refresh(id=selected?.id){try{const d=await request('/api/polls');P(d.polls);if(id)S((await request('/api/polls/'+id)).poll)}catch(e){M(e instanceof Error?e.message:'조회 실패')}}
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(editing||busy)return;const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000);return ()=>clearInterval(t)},[selected?.id,editing,busy]);
 async function action(body:unknown){if(!selected)return;B(true);M('');try{await request('/api/polls/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await refresh(selected.id);M('처리했습니다.')}catch(e){M(e instanceof Error?e.message:'처리 실패');await refresh(selected.id)}finally{B(false)}}
 async function save(e:any){B(true);M('');try{const poll={title:e.title,description:e.desc,duration:e.duration,meeting_mode:e.availability.meetingMode||'online',expected_count:expected,candidates:Object.entries(e.availability.days as Record<string,string[]>).flatMap(([d,ts])=>ts.map(t=>d+'T'+t))};if(!poll.candidates.length||poll.candidates.length>200)throw Error('후보 시간을 1~200개 선택해 주세요.');const d=await request(editing==='add'?'/api/polls/'+selected!.id:'/api/polls',{method:editing==='add'?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing==='add'?{action:'add',revision:selected!.revision,poll}:poll)});E(null);await refresh(d.poll?.id||selected?.id);M('투표 링크를 복사해 참석자에게 보내 주세요.');return true}catch(e){M(e instanceof Error?e.message:'저장 실패');return false}finally{B(false)}}
 const responses=selected?.responses||[],ranked=selected?rankSlots(selected.candidates,responses):[];
 return <section className="poll-workspace"><div className="toolbar"><p>복수의 가능 시간을 모아, 모두 가능한 시간에 확정하세요.</p><button className="primary" onClick={()=>{E('create');EX(2);M('')}}>일정 투표 만들기</button><button disabled={busy} onClick={()=>refresh()}>새로고침</button></div>{message&&<p className="notice" role="status">{message}</p>}
 {editing?<section className="panel"><button disabled={busy} onClick={()=>E(null)}>← 투표 목록</button><label>예상 참석 인원 (주최자 제외)<input type="number" min={1} max={100} disabled={editing==='add'} value={expected} onChange={e=>EX(Number(e.target.value))}/></label><p>예상 인원 이상이 응답하고, 응답자 전원이 선택한 시간만 확정할 수 있습니다. 공통 시간이 없으면 후보 시간을 추가하세요.</p><EventEditor key={editing+selected?.id} initial={editing==='add'&&selected?{id:selected.id,title:selected.title,desc:selected.description,duration:selected.duration,color:'blue',team:false,active:true,availability:{days:{},source:'manual',updatedAt:new Date().toISOString(),meetingMode:selected.meeting_mode}}:undefined} team={false} hours={hours} range={range} busy={busy} onSave={save} purpose="poll"/></section>:<>
 <div className="cards">{polls.map(p=><article className="eventcard blue" key={p.id}><span className="tag">{p.status==='open'?'응답 모집 중':p.status==='confirmed'?'확정':'종료'}</span><h2>{p.title}</h2><p>{p.duration}분 · 예상 {p.expected_count}명</p><button onClick={()=>refresh(p.id)}>응답 결과 보기</button><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/poll/'+p.id);M('투표 링크를 복사했습니다.')}catch{M('복사하지 못했습니다. 다시 시도해 주세요.')}}}>링크 복사</button></article>)}</div>{!polls.length&&<p className="notice">아직 일정 투표가 없습니다. 후보 시간을 정하고 첫 투표를 만들어 보세요.</p>}
 {selected&&<section className="panel"><h2>{selected.title}</h2><p>{responses.length}명 응답 / 예상 {selected.expected_count}명 · 한국시간</p>{selected.status==='confirmed'&&<p className="notice">확정: {selected.selected_slot?.replace('T',' ')} · 캘린더 등록과 참석자 이메일 발송을 요청했습니다.</p>}{selected.status==='cancelled'&&<p>종료된 투표입니다.</p>}
 <details><summary>참석자 응답 확인 ({responses.length}명)</summary>{responses.map(r=><p key={r.id}><strong>{r.name}</strong> · {r.email}<br/>{r.choices.length?r.choices.map(s=>s.replace('T',' ')).join(', '):'가능한 시간 없음'}</p>)}</details>
 {selected.status==='open'&&<><p>아래 순서는 참석 가능 인원이 많은 시간 우선입니다. 확정 전에 주최자 캘린더를 다시 확인합니다. 예상한 참석자들이 맞는지 응답 명단도 확인해 주세요.</p>{!ranked.some(r=>r.count===responses.length&&responses.length>=selected.expected_count)&&<p className="notice">아직 전원 가능한 시간이 없습니다. 응답을 기다리거나 후보 시간을 추가해 주세요.</p>}<div className="poll-results">{ranked.map(r=><div className="poll-result" key={r.slot}><span>{r.slot.replace('T',' ')}<br/><strong>{r.count} / {responses.length}명 가능</strong></span><button className="primary" disabled={busy||responses.length<selected.expected_count||r.count!==responses.length||new Date(r.slot+':00+09:00')<=new Date()} onClick={()=>{if(window.confirm(r.slot.replace('T',' ')+'에 확정하고 참석자에게 알릴까요?'))void action({action:'confirm',slot:r.slot,revision:selected.revision})}}>이 시간 확정</button></div>)}</div><button disabled={busy} onClick={()=>{EX(selected.expected_count);E('add');M('')}}>후보 시간 추가</button></>}
 {selected.status!=='cancelled'&&<button className="delete-page" disabled={busy} onClick={()=>{if(window.confirm(selected.status==='confirmed'?'모임을 취소하고 참석자에게 알릴까요?':'응답 모집을 종료할까요?'))void action({action:'cancel',revision:selected.revision})}}>{selected.status==='confirmed'?'확정 모임 취소':'투표 종료'}</button>}</section>}</>}
 </section>
}
