'use client';
import {useEffect,useState} from 'react';
import type {Poll} from '@/lib/polls/model';
export default function PollPage({id}:{id:string}){
 const [poll,P]=useState<Poll|null>(null),[choices,C]=useState<string[]>([]),[name,N]=useState(''),[email,EM]=useState(''),[credential,K]=useState<{id:string;key:string}|null>(null),[busy,B]=useState(false),[message,M]=useState(''),[saved,S]=useState(false),[revision,R]=useState(0);
 useEffect(()=>{try{const hash=new URLSearchParams(location.hash.slice(1)),raw=localStorage.getItem('moa-vote-'+id);const value=hash.has('key')?{id:hash.get('response'),key:hash.get('key')}:raw?JSON.parse(raw):null;const valid=(s:unknown)=>typeof s==='string'&&/^[a-f0-9-]{36}$/.test(s);K(value&&valid(value.id)&&valid(value.key)?value:{id:crypto.randomUUID(),key:crypto.randomUUID()})}catch{K({id:crypto.randomUUID(),key:crypto.randomUUID()})}},[id]);
 useEffect(()=>{if(!credential)return;const c=new AbortController();fetch('/api/poll/'+id,{headers:{'x-response-id':credential.id,'x-response-key':credential.key},cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);P(d.poll);if(d.response){N(d.response.name);EM(d.response.email);C(d.response.choices);S(true)}}).catch(e=>{if(e.name!=='AbortError')M(e.message)});return ()=>c.abort()},[id,credential,revision]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!credential)return;B(true);M('');try{try{localStorage.setItem('moa-vote-'+id,JSON.stringify(credential))}catch{}const r=await fetch('/api/poll/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...credential,name,email,choices,consent:true}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error);S(true);M('응답을 저장했습니다. 주최자가 시간을 확정하면 이메일로 알려드립니다.')}catch(e){M(e instanceof Error?e.message:'응답을 저장하지 못했습니다. 다시 시도해 주세요.')}finally{B(false)}}
 const days=[...new Set(poll?.candidates.map(s=>s.slice(0,10)))];
 return <main className="public-booking"><a className="brand" href="/">모아타임.</a><section className="panel public-panel"><span className="tag">GROUP SCHEDULING</span><h1>{poll?.title||'일정 투표'}</h1>{message&&<p className="notice" role="status">{message}</p>}{!poll&&<button onClick={()=>R(n=>n+1)}>다시 불러오기</button>}{poll&&<><button disabled={busy} onClick={()=>R(n=>n+1)}>최신 투표 확인</button><p>{poll.description}</p><p>{poll.duration}분 · {poll.meeting_mode==='offline'?'오프라인':'온라인'} · 한국시간</p>{poll.status==='confirmed'?<div className="notice"><h2>모임 시간이 확정되었습니다</h2><p>{poll.selected_slot?.replace('T',' ')}</p></div>:poll.status==='cancelled'?<p className="notice">종료되거나 취소된 모임입니다.</p>:<form className="public-form" onSubmit={save}><h2>가능한 시간을 모두 선택해 주세요</h2><p>로그인 없이 참여할 수 있습니다. 가능한 시간이 없으면 선택하지 않고 제출해 주세요. 다른 참석자의 이름·이메일은 공개되지 않습니다.</p><fieldset disabled={busy}>{days.map(day=><div key={day} className="poll-day"><h3>{day}</h3><div className="slots">{poll.candidates.filter(s=>s.startsWith(day)).map(slot=><button type="button" key={slot} aria-pressed={choices.includes(slot)} className={choices.includes(slot)?'picked':''} disabled={new Date(slot+':00+09:00')<=new Date()} onClick={()=>C(choices.includes(slot)?choices.filter(s=>s!==slot):[...choices,slot])}>{slot.slice(11)}</button>)}</div></div>)}<p>{choices.length}개 선택됨</p><label>이름<input required maxLength={80} value={name} onChange={e=>N(e.target.value)} autoComplete="name"/></label><label>확정 알림 이메일<input required type="email" maxLength={200} value={email} onChange={e=>EM(e.target.value)} autoComplete="email"/></label><label><input type="checkbox" required/>응답 저장 및 모임 확정·취소 이메일 수신에 동의합니다.</label><button className="primary full" disabled={!credential}>{busy?'저장 중…':saved?'응답 수정':'응답 제출'}</button></fieldset></form>}{saved&&credential&&<div className="notice"><p>이 브라우저에서 다시 응답을 수정할 수 있습니다. 다른 기기에서 수정하려면 전용 링크를 보관해 주세요.</p><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/poll/'+id+'#response='+credential.id+'&key='+credential.key);M('본인 응답 수정 링크를 복사했습니다. 다른 사람에게 공유하지 마세요.')}catch{M('링크를 복사하지 못했습니다.')}}}>내 응답 수정 링크 복사</button></div>}</>}</section></main>
}
