"use client";
import {useEffect,useState} from 'react';
import {CalendarDays,Clock3,ShieldCheck} from 'lucide-react';
type Data={event:{title:string;desc:string;duration:number};slots:string[];mode:string;user:{name:string;email:string}|null};
export default function BookingPage({id}:{id:string}){
  const [data,D]=useState<Data|null>(null),[day,DAY]=useState(''),[time,T]=useState(''),[error,E]=useState(''),[loading,L]=useState(false),[saving,S]=useState(false),[calendarSynced,CS]=useState(false),[done,DONE]=useState(false),[bookingId,ID]=useState('');
  useEffect(()=>{ID(crypto.randomUUID())},[]);
  useEffect(()=>{const c=new AbortController();L(true);T('');E('');fetch('/api/public/'+id+(day?'?day='+day:''),{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}).then(D).catch(e=>{if(e.name!=='AbortError')E(e.message)}).finally(()=>{if(!c.signal.aborted)L(false)});return ()=>c.abort()},[id,day]);
  const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'}),max=new Date(Date.now()+90*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
  async function reserve(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);S(true);E('');try{const r=await fetch('/api/public/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:bookingId,day,time,name:f.get('name'),phone:f.get('phone')||'',channels:f.getAll('channels'),notificationConsent:f.get('consent')==='on'})});const d=await r.json();if(!r.ok)throw Error(d.error);CS(d.calendar?.synced===true);DONE(true)}catch(e){E(e instanceof Error?e.message:'예약에 실패했습니다.')}finally{S(false)}}
  return <div className="public-booking"><a href="/" className="brand"><span className="logo"><CalendarDays/></span>모아타임.</a><section className="panel public-panel"><span className="tag">BOOK A TIME</span><h1>{done?'예약이 확정되었습니다':data?.event.title||'일정 예약'}</h1><p>{data?.event.desc}</p>{data&&<p><Clock3 size={15} style={{display:'inline',verticalAlign:'middle'}}/> {data.event.duration}분 · 한국시간 (Asia/Seoul)</p>}{error&&<div className="notice" role="alert">{error}</div>}
  {done?<><h2>{day} · {time}</h2><p>{data?.user?.email}</p><div className="notice">{data?.mode==='live'?'예약자와 주최자 이메일로 알림 발송을 요청했습니다.':'예약은 저장되었지만 현재 알림 발송이 꺼져 있거나 모의 발송 상태입니다.'}</div><p>{calendarSynced?'주최자의 Google 캘린더에 등록되었습니다.':'예약은 확정되었지만 주최자 캘린더 등록은 재시도가 필요합니다. 주최자에게 알려 주세요.'}</p><p>변경·취소가 필요한 경우 주최자에게 요청해 주세요.</p></>:<><label className="public-date">주최자와 만날 날짜<input type="date" min={today} max={max} value={day} onChange={e=>DAY(e.target.value)}/></label>{loading&&<p role="status">주최자의 캘린더에서 가능한 시간을 확인하고 있습니다…</p>}{!loading&&data&&day&&!error&&<><div className="slots">{data.slots.map(s=><button key={s} className={s===time?'picked':''} onClick={()=>T(s)}>{s}</button>)}</div>{!data.slots.length&&<p>이 날짜에는 예약 가능한 시간이 없습니다.</p>}</>}
  {data&&!data.user?<div className="notice"><p>예약자 확인과 알림 수신을 위해 Google 로그인이 필요합니다. 예약자의 캘린더 권한은 요청하지 않습니다.</p><a className="authbutton" href={'/auth/google?next='+encodeURIComponent('/book/'+id)}>Google로 계속하기</a></div>:time&&data?.user&&<form className="public-form" onSubmit={reserve}><label>이름<input name="name" required maxLength={80} defaultValue={data.user.name}/></label><label>이메일<input readOnly value={data.user.email}/></label><label>휴대전화 (문자·알림톡 선택 시)<input name="phone" type="tel" placeholder="01012345678"/></label><fieldset className="channel-options"><legend>예약 확정·취소 알림</legend><p>예약자와 주최자에게 이메일을 보냅니다.</p><label><input type="checkbox" name="channels" value="sms"/>문자도 받기</label><label><input type="checkbox" name="channels" value="kakao"/>카카오 알림톡도 받기</label><label><input type="checkbox" name="consent" required/>예약 처리와 선택한 채널의 예약 알림을 위해 입력한 연락처를 사용하는 것에 동의합니다.</label></fieldset><button className="primary full" disabled={saving||loading||!!error}>{saving?'예약 확인 중…':'예약 확정'}</button></form>}</>}
  <div className="footnote"><ShieldCheck size={15}/>주최자의 기존 일정을 제외한 시간만 표시합니다. 본인 일정은 직접 확인해 선택해 주세요.</div></section></div>
}
