"use client";
import {useState,useEffect,useRef} from 'react';
import BookingsCalendar from '@/components/bookings-calendar';
import {bookingStatus} from '@/lib/bookings/status';
import EventEditor from '@/components/event-editor';
import NotificationSettings from '@/components/notification-settings';
import {CalendarDays,Link2,Clock3,Users,Settings,Plus,ArrowUpRight,ChevronRight,ChevronLeft,ChevronDown,Video,Search,X,Check,Globe,ShieldCheck,LayoutGrid,ArrowRight,CalendarCheck} from 'lucide-react';
const seed=[{id:'coffee',title:'가볍게 나누는 커피챗',desc:'새로운 연결의 시작, 편하게 이야기 나눠요.',duration:30,color:'blue',team:false,active:true},{id:'project',title:'프로젝트 상담',desc:'아이디어를 함께 구체화하는 시간입니다.',duration:60,color:'purple',team:false,active:true},{id:'sync',title:'빠른 싱크업',desc:'짧고 집중해서, 필요한 이야기만 나눠요.',duration:15,color:'orange',team:false,active:true},{id:'team',title:'서비스 데모 미팅',desc:'우리 팀과 함께 서비스를 살펴보세요.',duration:30,color:'green',team:true,active:true}];
export default function Home(){const [view,V]=useState('예약 페이지'),[team,T]=useState(false),[events,E]=useState<any[]>(seed),[bookings,B]=useState<any[]>([]),[hours,HS]=useState([false,true,true,true,true,true,false]),[range,R]=useState(['09:00','18:00']),[query,Q]=useState(''),[modal,M]=useState(''),[item,I]=useState<any>(seed[0]),[toast,N]=useState(''),[day,D]=useState(''),[time,H]=useState(''),[month,MO]=useState(new Date().getMonth()),[year,Y]=useState(new Date().getFullYear()),[ready,RR]=useState(false),[busy,BS]=useState(false),[revision,REV]=useState(0),[user,U]=useState<any>(null),[setup,SETUP]=useState(false),[mode,MODE]=useState('off'),[slots,SLOTS]=useState<string[]>([]),[slotError,SE]=useState(''),[slotLoading,SL]=useState(false);
const [calendarSync,CS]=useState<{checkedAt:string;ok:boolean}|null>(null);
const clockOffset=useRef(0);
const [now,setNow]=useState(()=>Date.now());
useEffect(()=>{const update=()=>setNow(Date.now()+clockOffset.current);const timer=setInterval(update,15000);window.addEventListener('focus',update);return ()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[]);
const notify=(s:string)=>{N(s);setTimeout(()=>N(''),4000)};
useEffect(()=>{fetch('/api/workspace').then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>{if(!d.user&&!d.setupRequired){location.replace('/');return}if(Number.isFinite(d.serverNow)){clockOffset.current=d.serverNow-Date.now();setNow(d.serverNow)}if(d.calendarSync)CS(d.calendarSync);if(d.events)E(d.events);if(d.bookings)B(d.bookings);if(d.hours)HS(d.hours);if(d.range)R(d.range);REV(d.revision||0);U(d.user);SETUP(!!d.setupRequired);MODE(d.notifications?.mode||'off');RR(true);let id=new URLSearchParams(location.search).get('book');if(id){I((d.events||seed).find((e:any)=>e.id===id)||seed[0]);M('book')}}).catch(()=>notify('저장소를 불러오지 못했습니다. 다시 시도해 주세요.'))},[]);
async function save(data:any){if(!user){M('login');notify(setup?'Supabase 연결 설정이 필요합니다.':'Google 로그인 후 저장할 수 있습니다.');return false}BS(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,revision})});const result:any=await r.json();if(!r.ok)throw Error(result.error);REV(result.revision);if(result.notificationMode)MODE(result.notificationMode);if(result.events)E(result.events);else if(data.events)E(data.events);if(result.calendarSync)CS(result.calendarSync);if(data.bookings)B(data.bookings);notify(result.calendarPending?'예약은 저장했습니다. 설정 및 연동에서 캘린더 반영을 재시도해 주세요.':'저장했습니다');return true}catch(e){notify(e instanceof Error?e.message:'저장하지 못했습니다.');return false}finally{BS(false)}}
async function copy(e:any){try{const r=await fetch('/api/public-links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:e.id})});const data=await r.json();if(!r.ok)throw Error(data.error);await navigator.clipboard.writeText(location.origin+data.path);notify('공개 예약 링크를 복사했습니다')}catch(error){notify(error instanceof Error?error.message:'링크를 복사하지 못했습니다.')}}
useEffect(()=>{if(modal!=='book'||!day)return;const controller=new AbortController();SL(true);SLOTS([]);SE('');H('');fetch('/api/availability?eventId='+encodeURIComponent(item.id)+'&day='+day,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}).then(d=>SLOTS(d.slots)).catch(e=>{if(e.name!=='AbortError')SE(e.message)}).finally(()=>{if(!controller.signal.aborted)SL(false)});return ()=>controller.abort()},[day,item.id,modal]);
useEffect(()=>{const q=new URLSearchParams(location.search);if(q.has('auth_error'))notify(q.get('auth_error')==='calendar'?'로그인되었습니다. 캘린더 연결 설정을 확인하고 다시 연결해 주세요.':'Google 로그인 설정을 확인하고 다시 시도해 주세요.')},[]);
useEffect(()=>{if(!modal)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')M('')};document.addEventListener('keydown',close);return ()=>document.removeEventListener('keydown',close)},[modal]);

useEffect(()=>{if(busy||modal||!ready)return;let active=true;const refresh=async()=>{try{const r=await fetch('/api/workspace',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(!active)return;if(!d.user&&!d.setupRequired){location.replace('/');return}if(d.bookings)B(d.bookings);if(d.calendarSync)CS(d.calendarSync);if(d.events)E(d.events);REV(d.revision||0)}catch{}};void refresh();const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[view,busy,modal,ready]);
const upcomingCount=bookings.filter(b=>bookingStatus(b,now)!=='completed').length;
const filtered=events.filter(e=>e.team===team&&e.title.includes(query));
const open=(e:any)=>{I(e);D('');H('');M('book')};
return <div className="shell"><aside><a className="brand" href="/app"><span className="logo"><CalendarDays size={22}/></span>모아타임<span className="dot">.</span></a><button className="workspace" onClick={()=>T(!team)}><span className="avatar">{team?'M':'나'}</span><span><strong>{team?'모아 스튜디오':'내 워크스페이스'}</strong><small>{team?'팀 워크스페이스':'개인 워크스페이스'}</small></span><ChevronDown size={15}/></button><span className="navlabel">WORKSPACE</span><nav>{[[Link2,'예약 페이지'],[CalendarDays,'예약된 일정'],[Clock3,'가능 시간'],[Users,'팀 관리'],[Settings,'설정 및 연동']].map(([Icon,title]:any)=><button key={title} className={view===title?'active':''} onClick={()=>V(title)}><Icon size={19}/>{title}{title==='예약된 일정'&&upcomingCount>0&&<em>{upcomingCount}</em>}</button>)}</nav><div className="sidebottom"><div className="teamnote"><Users size={20}/><strong>함께라서 더 쉬운 일정 조율</strong><p>팀의 시간을 한곳에 모아보세요.</p><button onClick={()=>{T(true);V('팀 관리')}}>팀 워크스페이스 살펴보기 <ArrowRight size={14}/></button></div><button className="settings" onClick={()=>V('설정 및 연동')}><Settings size={18}/>설정 및 연동</button><button className="profile" onClick={()=>user?V('설정 및 연동'):M('login')}><span className="avatar neutral">나</span><span><strong>{user?.name||'Google 로그인 필요'}</strong><small>{user?.email||'Google로 로그인하기'}</small></span><ChevronRight size={16}/></button></div></aside><div className="mainwrap"><header><span>워크스페이스 <ChevronRight size={13}/><b>{view}</b></span><div><span className="pill">{setup?'연결 설정 필요':user?'Supabase 연결':'미리보기'}</span>{user?<button onClick={async()=>{await fetch('/auth/logout',{method:'POST'});location.assign('/')}}>로그아웃</button>:<button onClick={()=>M('login')}>로그인 <ArrowUpRight size={15}/></button>}</div></header><main>{calendarSync&&<div className="notice" role="status">{calendarSync.ok?`Google 캘린더 동기화 · ${new Date(calendarSync.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} (한국시간)`:<>Google 캘린더를 확인하지 못해 신규 예약을 잠시 중지했습니다. <a href="/auth/google">Google 다시 연결</a></>}</div>}<div className="heading"><div><div className="eyebrow">MAKE TIME FOR WHAT MATTERS</div><h1>{view}</h1><p>{view==='예약 페이지'?'링크 하나로, 서로에게 딱 맞는 시간을 만나세요.':view==='예약된 일정'?'다가오는 만남을 한눈에 확인하세요.':view==='가능 시간'?'미팅에 집중할 시간을 정해두세요.':view==='팀 관리'?'개인의 시간을 모아, 팀의 가능성을 넓히세요.':'Google 계정과 캘린더 연결을 관리하세요.'}</p></div>{view==='예약 페이지'&&<button className="primary" onClick={()=>M('create')}><Plus size={18}/>예약 페이지 만들기</button>}</div>
{view==='예약 페이지'&&<><section className="overview"><div className="overviewcopy"><span className="overviewicon"><CalendarCheck size={24}/></span><div><strong>좋은 만남은, 간편한 예약에서 시작되니까.</strong><p>가능한 시간을 설정하고 나만의 예약 링크를 공유해 보세요.</p><button onClick={()=>V('가능 시간')}>가능 시간 설정하기 <ArrowRight size={15}/></button></div></div><div className="miniweek"><div>MY AVAILABILITY <span>Asia/Seoul</span></div><section>{['월','화','수','목','금'].map((d,i)=><div key={d}><small>{d}</small><i className={hours[i+1]?'on':''}/><i className={hours[i+1]?'on':''}/></div>)}</section></div></section><div className="toolbar"><div className="tabs"><button className={!team?'chosen':''} onClick={()=>T(false)}>개인 예약 페이지 <span>{events.filter(e=>!e.team).length}</span></button><button className={team?'chosen':''} onClick={()=>T(true)}>팀 예약 페이지 <span>{events.filter(e=>e.team).length}</span></button></div><label className="search"><Search size={17}/><input aria-label="예약 페이지 검색" placeholder="예약 페이지 검색" value={query} onChange={e=>Q(e.target.value)}/></label></div><div className="sectionmeta"><span>{team?'팀':'내'} 예약 페이지 <b>{filtered.length}</b></span><span><LayoutGrid size={14}/>카드 보기</span></div><div className="cards">{filtered.map(e=><article className={'eventcard '+e.color} key={e.id}><div className="cardtop"><span className="eventicon">{e.team?<Users size={23}/>:<Video size={23}/>}</span><label className="switch"><input type="checkbox" aria-label={e.title+' 활성화'} checked={e.active} onChange={()=>save({events:events.map(x=>x.id===e.id?{...x,active:!x.active}:x)})}/><span/></label></div><span className="eventkind">{e.team?'팀 예약 · 공동 참석':'일대일 예약'}</span><h2>{e.title}</h2><p>{e.desc}</p><div className="eventdetails"><span><Clock3 size={15}/>{e.duration}분</span><span><Video size={15}/>온라인 미팅</span></div><small className="availability-state">{e.availability?`${Object.values(e.availability.days as Record<string,string[]>).filter(s=>s.length).length}일 가능 시간 설정됨`:'가능한 날짜를 먼저 설정해 주세요'}</small><button className="edit-availability" onClick={()=>{I(e);M('edit')}}>날짜·가능 시간 설정</button><div className="cardbottom"><button onClick={()=>open(e)}>미리보기 <ArrowUpRight size={14}/></button><button className="copy" onClick={()=>copy(e)}><Link2 size={15}/>링크 복사</button></div></article>)}<button className="addcard" onClick={()=>M('create')}><span><Plus size={25}/></span><strong>새로운 만남을 만들어보세요</strong><p>목적에 맞는 예약 페이지를 추가하세요.</p></button></div><section className="how">{[['예약 페이지 만들기','미팅 목적과 시간을 정해요.'],['나만의 링크 공유하기','이메일, 메신저 어디든 간편하게.'],['딱 맞는 시간에 만나기','상대방이 가능한 시간을 선택해요.']].map(([t,p],i)=><div key={t}><span className="step">0{i+1}</span><strong>{t}</strong><p>{p}</p></div>)}</section><div className="footnote"><ShieldCheck size={14}/>{setup?'Supabase와 Google 연결값을 설정하면 저장과 캘린더 조회를 사용할 수 있습니다.':user?'페이지별로 저장한 가능 시간에서 확정 예약을 제외해 보여줍니다.':'Google로 로그인하여 예약 페이지를 만들고 공유하세요.'}</div></>}
{view==='가능 시간'&&<section className="panel"><h2>주간 가능 시간 템플릿</h2><p>예약 페이지에서 기간을 채울 때 사용하는 기본값입니다. 페이지별 날짜·시간은 예약 페이지 카드에서 설정하세요.</p><p>서울 · Asia/Seoul (UTC+09:00)</p>{['일요일','월요일','화요일','수요일','목요일','금요일','토요일'].map((d,i)=><div className="hoursrow" key={d}><label><input type="checkbox" checked={hours[i]} onChange={e=>HS(hours.map((v,j)=>j===i?e.target.checked:v))}/>{d}</label>{hours[i]?<><input aria-label={d+' 시작'} type="time" value={range[0]} onChange={e=>R([e.target.value,range[1]])}/><span>—</span><input aria-label={d+' 종료'} type="time" value={range[1]} onChange={e=>R([range[0],e.target.value])}/></>:<span className="muted">예약 불가</span>}</div>)}<p>선택한 모든 요일에 동일한 시간이 적용됩니다.</p><button className="primary" disabled={busy} onClick={()=>range[0]<range[1]?save({hours,range}):notify('종료 시간을 시작 시간 이후로 설정해 주세요.')}>변경사항 저장</button></section>}
{view==='예약된 일정'&&<BookingsCalendar bookings={bookings} now={now} busy={busy} onCancel={id=>save({bookings:bookings.filter(b=>b.id!==id)})}/>}
{view==='팀 관리'&&<section className="panel"><span className="tag">TEAM WORKSPACE</span><h2>모아 스튜디오</h2><p>팀원 모두가 참석하는 공동 예약 페이지를 관리하세요.</p><div className="teamfeatures"><div><Users/><h3>함께 참석하는 미팅</h3><p>팀의 공통 가능 시간을 설정하고 예약받으세요.</p><button onClick={()=>{T(true);V('예약 페이지')}}>팀 예약 페이지 보기 <ArrowRight size={16}/></button></div><div><ShieldCheck/><h3>Google 계정 하나로</h3><p>개인과 기업 모두 Google로 간편하게 시작합니다.</p><button onClick={()=>M('login')}>Google로 시작하기 <ArrowRight size={16}/></button></div></div><div className="notice">현재 팀 페이지는 주최자 한 명의 캘린더를 기준으로 동작합니다. 팀원 초대와 여러 캘린더 소유자의 공동 참석 처리는 별도 확장이 필요합니다.</div></section>}
{view==='설정 및 연동'&&<><section className="panel"><h2>Google 계정 및 캘린더</h2><div className="integration"><span className="google">G</span><div><h3>{user?.email||'Google 계정 연결'}</h3><p>표시 중인 Google 캘린더의 바쁜 시간을 제외합니다.</p></div><a className="primary" href="/auth/google">{user?'다시 연결':'Google로 연결'}</a></div><div className="notice">개인·기업 모두 Google 로그인만 제공합니다. Google 가져오기는 가능 시간 설정에서 실행합니다. 예약 화면은 저장된 시간만 조회합니다.</div></section><NotificationSettings/></>}
</main><footer><span>© 2026 모아타임</span><span>시간을 모아, 더 좋은 만남으로.</span><span><Globe size={13}/>한국어 · KST</span></footer></div>
{modal&&<div className="overlay" onClick={()=>M('')}><section role="dialog" aria-modal="true" aria-label="예약 및 로그인" className={'modal '+(['book','create','edit'].includes(modal)?'wide':'')} onClick={e=>e.stopPropagation()}><button className="close" aria-label="닫기" onClick={()=>M('')}><X/></button>{(modal==='create'||modal==='edit')&&<EventEditor key={modal==='edit'?item.id:'new'} initial={modal==='edit'?item:undefined} team={team} hours={hours} range={range} busy={busy} onSave={async event=>{const ok=await save({events:modal==='edit'?events.map(e=>e.id===event.id?event:e):[...events,event]});if(ok)M('');return ok}}/>}
{modal==='login'&&<div className="auth"><span className="logo"><CalendarDays/></span><h2>반가워요, 모아타임입니다</h2><p>Google 계정으로 로그인하고 캘린더를 연결하세요.</p><a className="authbutton" href="/auth/google"><span className="google">G</span>Google로 계속하기</a><p>개인도, 팀도 Google 계정으로 시작하세요.</p><div className="notice">{setup?'Supabase 및 Google OAuth 연결값 설정이 필요합니다.':'캘린더의 바쁜 시간만 예약 가능 시간 계산에 사용합니다. 일정 제목과 내용을 예약자에게 공개하지 않습니다.'}</div></div>}
{modal==='book'&&<div className="booklayout"><div className="bookinfo"><span className="avatar">{item.team?'M':'나'}</span><p>{item.team?'모아 스튜디오':'모아타임'}</p><h2>{item.title}</h2><p>{item.desc}</p><span><Clock3 size={17}/>{item.duration}분</span><span><Video size={17}/>온라인 미팅</span><span><Globe size={17}/>Asia/Seoul</span><div className="notice">{mode==='live'?'예약 확정·취소 시 예약자와 주최자에게 이메일을 보냅니다.':'알림 발송은 '+(mode==='dry-run'?'모의 발송':'꺼짐')+' 상태입니다. 실제 메시지는 발송되지 않습니다.'}</div></div><div className="datepick"><h3>날짜와 시간을 선택하세요</h3>{!item.active?<p>현재 예약을 받고 있지 않습니다.</p>:<><div className="month"><button aria-label="이전 달" onClick={()=>{let d=new Date(year,month-1,1);MO(d.getMonth());Y(d.getFullYear());D('')}}><ChevronLeft/></button><strong>{year}년 {month+1}월</strong><button aria-label="다음 달" onClick={()=>{let d=new Date(year,month+1,1);MO(d.getMonth());Y(d.getFullYear());D('')}}><ChevronRight/></button></div><div className="calendar">{['일','월','화','수','목','금','토'].map(d=><small key={d}>{d}</small>)}{Array.from({length:new Date(year,month,1).getDay()},(_,i)=><span key={'x'+i}/>)}{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=>{const date=new Date(year,month,i+1),ds=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return <button key={i} disabled={!item.availability?.days[ds]?.length||date<new Date(new Date().setHours(0,0,0,0))} className={day===ds?'picked':''} onClick={()=>{D(ds);H('')}}>{i+1}</button>})}</div>{day&&<><p>{day} · 가능한 시간</p>{slotLoading&&<p role="status">저장된 가능 시간 확인 중…</p>}{slotError&&<p role="alert">{slotError}</p>}{!slotLoading&&!slotError&&!slots.length&&<p>예약 가능한 시간이 없습니다.</p>}<div className="slots">{slots.map(t=><button key={t} className={t===time?'picked':''} onClick={()=>H(t)}>{t}</button>)}</div></>}{day&&time&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await save({bookings:[...bookings,{id:crypto.randomUUID(),eventId:item.id,title:item.title,duration:item.duration,day,time,name:f.get('name'),email:f.get('email'),phone:f.get('phone')||'',channels:['email',...f.getAll('channels')],notificationConsent:f.get('consent')==='on'}]}))M('success')}}><label>이름<input name="name" required maxLength={80}/></label><label>이메일<input name="email" type="email" required maxLength={200}/></label><label>휴대전화 (문자·알림톡 선택 시)<input name="phone" type="tel" placeholder="01012345678"/></label><fieldset className="channel-options"><legend>예약 알림</legend><p>이메일은 예약자·주최자 양쪽에 발송합니다.</p><label><input type="checkbox" name="channels" value="sms"/>문자</label><label><input type="checkbox" name="channels" value="kakao"/>카카오 알림톡</label><label><input type="checkbox" name="consent" required/>입력한 수신자의 예약 확정·취소 알림 수신을 확인했습니다.</label></fieldset><button className="primary full" disabled={busy||slotLoading||!!slotError}>예약 확정</button></form>}</>}</div></div>}
{modal==='success'&&<div className="auth"><span className="successicon"><Check/></span><h2>예약이 저장되었습니다</h2><p>{item.title}</p><h3>{day} · {time}</h3><p>{mode==='live'?'예약 알림을 발송 대기열에 등록했습니다. 접수 결과는 설정에서 확인하세요.':'예약은 저장되었으며, 현재 알림 모드에서는 실제 메시지를 발송하지 않습니다.'}</p><button className="primary full" onClick={()=>{M('');V('예약된 일정')}}>예약된 일정 확인하기</button></div>}</section></div>}{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</div>}
function mins(s:string){return Number(s.slice(0,2))*60+Number(s.slice(3))}
